<?php $version = 10; ?>

<title>Wheels4Meals</title>
<meta name="viewport" content="width=device-width, initial-scale=1">

<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.min.js"></script>
<script src="<?= $root ?>/scripts/jquery.toast.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.3/js/swiper.min.js"></script>
<script src="<?= $root ?>/scripts/common.js?<?= $version ?>"></script>
<script src="<?= $root ?>/scripts/admin.js?<?= $version ?>"></script>
<script src="<?= $root ?>/scripts/register.js?<?= $version ?>"></script>
<script src="<?= $root ?>/scripts/company.js?<?= $version ?>"></script>
<script src="<?= $root ?>/scripts/donation.js?<?= $version ?>"></script>

<link href="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css" rel="stylesheet">
<link href="<?= $root ?>/styles/jquery.toast.min.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.3/css/swiper.min.css">
<link href="<?= $root ?>/styles/main.css?<?= $version ?>" rel="stylesheet" type="text/css" media="all">

<!-- generated by realfavicongenerator.net -->
<link rel="apple-touch-icon" sizes="180x180" href="/images/favicon/apple-touch-icon.png">
<link rel="icon" type="image/x-icon" sizes="32x32" href="/images/favicon/favicon32.ico">
<link rel="icon" type="image/x-icon" sizes="16x16" href="/images/favicon/favicon16.ico">
<link rel="manifest" href="/images/favicon/site.webmanifest">
<link rel="mask-icon" href="/images/favicon/safari-pinned-tab.svg" color="#bb7722">
<meta name="msapplication-TileColor" content="#00aba9">
<meta name="msapplication-config" content="/images/favicon/browserconfig.xml">
<meta name="theme-color" content="#ffffff">

<?php if ($showBanner) { ?>
<?php } ?>
